version: '3.7'
services:
  java_ait_standard_guideline:
    image: ait/buddytest:latest
    container_name: buddytest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8092:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/buddy_test
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres