#Profile: dev
restclient:
  url:
    jsonplaceholder-client: https://jsonplaceholder.typicode.com
    payment-client: https://afa39192-d126-42c7-8e53-497c1bbb5cfb.mock.pstmn.io
    reqres-client: https://reqres.in/api

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/buddy_test
    username: postgres
    password: postgres
  flyway:
    enabled: true