#Profile: dev
restclient:
  url:
    jsonplaceholder-client: https://jsonplaceholder.typicode.com
    payment-client: https://buddy-test.mocklab.io/api
    reqres-client: https://reqres.in/api

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/buddy_test
    username: postgres
    password: postgres
  flyway:
    enabled: true