-- Drop Table Customer
DROP TABLE IF EXISTS CUSTOMER;

-- Drop Table Product
DROP TABLE IF EXISTS PRODUCT;

-- Drop Table Orders
DROP TABLE IF EXISTS ORDERS;

-- Drop Table Order Details
DROP TABLE IF EXISTS ORDER_DETAILS;


-- Create Table Customer
CREATE TABLE CUSTOMER (
    ID                  BIGINT PRIMARY KEY NOT NULL,
    NAME                VARCHAR(50) NOT NULL,
    EMAIL               VARCHAR(50) NOT NULL,
    PHONE_NUMBER        VARCHAR(15) NOT NULL,
    ADDRESS             VARCHAR(255) NOT NULL,
    CREATED_AT          TIMESTAMP WITH TIME ZONE,
    CREATED_BY          BIGINT,
    UPDATED_AT          TIMESTAMP WITH TIME ZONE,
    UPDATED_BY          BIGINT,
    DELETED_AT          TIMESTAMP WITH TIME ZONE,
    DELETED_BY          BIGINT
);

-- Create Table Product
CREATE TABLE PRODUCT
(
    ID                  BIGINT PRIMARY KEY NOT NULL,
    TYPE                VARCHAR(20) NOT NULL,
    SERI_NAME           VARCHAR(50) NOT NULL,
    PRICE               DOUBLE PRECISION NOT NULL,
    CREATED_AT          TIMESTAMP WITH TIME ZONE,
    CREATED_BY          BIGINT,
    UPDATED_AT          TIMESTAMP WITH TIME ZONE,
    UPDATED_BY          BIGINT,
    DELETED_AT          TIMESTAMP WITH TIME ZONE,
    DELETED_BY          BIGINT
) ;

-- Create Table Orders
CREATE TABLE ORDERS
(
    ID                  BIGINT PRIMARY KEY,
    CUSTOMER_ID         BIGINT NOT NULL,
    AMOUNT              DOUBLE PRECISION NOT NULL,
    ORDER_DATE          TIMESTAMP WITH TIME ZONE NOT NULL,
    ORDER_NUMBER        VARCHAR(20) NOT NULL,
    CREATED_AT          TIMESTAMP WITH TIME ZONE,
    CREATED_BY          BIGINT,
    UPDATED_AT          TIMESTAMP WITH TIME ZONE,
    UPDATED_BY          BIGINT,
    DELETED_AT          TIMESTAMP WITH TIME ZONE,
    DELETED_BY          BIGINT,
    CONSTRAINT FK_CUSTOMER
        FOREIGN KEY(CUSTOMER_ID)
            REFERENCES CUSTOMER(ID)
) ;

-- Create Table Order Details
CREATE TABLE ORDER_DETAILS
(
    ID                  BIGINT PRIMARY KEY,
    AMOUNT              DOUBLE PRECISION NOT NULL,
    PRICE               DOUBLE PRECISION NOT NULL,
    QUANTITY            BIGINT NOT NULL,
    PRODUCT_ID          BIGINT NOT NULL,
    CREATED_AT          TIMESTAMP WITH TIME ZONE,
    CREATED_BY          BIGINT,
    UPDATED_AT          TIMESTAMP WITH TIME ZONE,
    UPDATED_BY          BIGINT,
    DELETED_AT          TIMESTAMP WITH TIME ZONE,
    DELETED_BY          BIGINT,
    CONSTRAINT FK_PRODUCT
        FOREIGN KEY(PRODUCT_ID)
            REFERENCES PRODUCT(ID)
) ;